language: node_js
sudo: false
node_js:
  - 12
  - 11
  - 10
  - 9
install:
  - cd $TRAVIS_BUILD_DIR/application/ && npm install
  - cd $TRAVIS_BUILD_DIR/server/ && npm install
script:
  - cd $TRAVIS_BUILD_DIR/application/ && npm run build
